services:
    app:
        build: ./api
        env_file:
            - .env
        container_name: ${CONTAINER_NAME}
        ports:
            - ${APP_HOST_PORT}:${APP_CONTAINER_PORT}
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:15.3-alpine
        env_file:
            - .env
        container_name: ${DB_CONTAINER_NAME}
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 10s
            timeout: 30s
            retries: 5
            start_period: 30s